### ISSUE TITLE
Can't get local version to start

### ISSUE THREAD

**Issue by khaki32** [brandongregoryscott/beets#185]
I've followed all the stepts of the Contributing guide. However, when I try to run `npm start` I get the following error:

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/khakiaunt32/Projects/beets/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/khakiaunt32/Projects/beets/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/khakiaunt32/Projects/beets/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/khakiaunt32/Projects/beets/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
/home/khakiaunt32/Projects/beets/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/home/khakiaunt32/Projects/beets/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/khakiaunt32/Projects/beets/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/khakiaunt32/Projects/beets/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/khakiaunt32/Projects/beets/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/khakiaunt32/Projects/beets/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/khakiaunt32/Projects/beets/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

Anything that I could have missed? Or something that I need to update/downgrade?

My Node version is 17.7.2

**Comment by brandongregoryscott** [comment]
Ooh, yeah - just switched to Node 17 using `nvm` and I'm seeing the same error. Can you try using node v14 and see if it boots up?

**Comment by brandongregoryscott** [comment]
Looks like this makes Node v17 work: `export NODE_OPTIONS=--openssl-legacy-provider && npm start`. But I would still recommend sticking with v14 since that's what I've been developing on. Found this flag on this Stackoverflow answer: https://stackoverflow.com/a/69746937/5534503

**Comment by khaki32** [comment]
Thanks! The project *loads* now, but I think I did something wrong with the Supbase set up as a part of that doesn't work. It's fine for now though.

**Comment by brandongregoryscott** [comment]
Let me know if I can help out there, too. A lot of the documentation around the Supabase setup was from memory so I might've missed a step.
